// Translation dictionaries for the chrome (nav/footer/meter/keyboard help) and
// the localized landing page, across the Core-8 languages.
//
// Strings are flat dotted keys. English (`en`) is the canonical, complete set;
// `t()` (see utils.ts) falls back to English for any key a language is missing,
// so a partial translation degrades gracefully instead of crashing.
//
// Deliberate scope: the TOOL and landing page are fully localized. The long-form
// reference pages (full FAQ, blog, decibel chart, calculator) stay English with
// hreflang — concise original localized copy beats machine-translated walls of
// audiology jargon (which also reads as "thin content" to Google/AdSense).

export type UIKey = keyof (typeof ui)["en"];

export const ui = {
  // ===========================================================================
  // ENGLISH — canonical / complete
  // ===========================================================================
  en: {
    // -- common / chrome --
    "common.skip": "Skip to content",
    "common.start": "Start measuring",
    "common.home": "Home",
    "common.language": "Language",
    "common.theme": "Toggle light / dark",
    "common.menu.open": "Open menu",
    "common.menu.close": "Close menu",
    "common.keyboard": "Keyboard shortcuts",

    // -- nav --
    "nav.meter": "Meter",
    "nav.decibelChart": "Decibel Chart",
    "nav.safeExposure": "Safe Exposure",
    "nav.classroom": "Classroom",
    "nav.blog": "Blog",
    "nav.faq": "FAQ",
    "nav.howItWorks": "How it works",
    "nav.accuracy": "Accuracy & calibration",
    "nav.about": "About",
    "nav.methodology": "Methodology",
    "nav.privacy": "Privacy",

    // -- footer --
    "footer.tools": "Tools",
    "footer.learn": "Learn",
    "footer.about": "About",
    "footer.tagline":
      "A free, private sound level meter that runs entirely in your browser. Audio never leaves your device.",
    "footer.rights": "All readings are reference estimates.",
    "footer.sources": "Built for accuracy · Sources",

    // -- meter UI --
    "meter.aria": "Live sound level meter",
    "meter.idle": "Microphone idle",
    "meter.measuring": "Measuring…",
    "meter.unavailable": "Unavailable",
    "meter.weight": "Weight",
    "meter.fast": "Fast",
    "meter.slow": "Slow",
    "meter.idleZone": "Idle",
    "meter.min": "Min",
    "meter.max": "Max",
    "meter.avg": "Avg",
    "meter.leq": "LAeq",
    "meter.spectrum": "Frequency spectrum",
    "meter.spectrumHint": "Start measuring to see live spectrum",
    "meter.history": "Level history · last 60 s",
    "meter.nioshLimit": "NIOSH 85 dB limit",
    "meter.stop": "Stop",
    "meter.reset": "Reset",
    "meter.calibrate": "Calibrate",
    "meter.exportCsv": "Export CSV",
    "meter.savePdf": "Save PDF",
    "meter.note":
      "Audio is processed locally and never leaves your device. A phone or laptop mic is not a calibrated meter — readings are reference estimates. Use the calibration offset to align against a known reference.",
    "meter.errUnsupported": "This browser does not support microphone access.",
    "meter.errDenied":
      "Microphone permission denied. Allow access and reload to measure. Audio stays on your device.",
    "meter.srSummary": "{db} decibels, {zone}. Average {avg}, max {max}.",
    "meter.report.title": "Sound Level Report",
    "meter.report.average": "average",
    "meter.report.metric": "Metric",
    "meter.report.value": "Value",
    "meter.report.note":
      "Generated by Online Sound Meter. Readings are uncalibrated reference estimates from a consumer microphone, not a substitute for a Type 1/2 sound level meter. Sources: NIOSH, WHO, NIDCD.",

    // -- safety zones (match engine ids) --
    "zone.quiet": "Quiet",
    "zone.moderate": "Moderate",
    "zone.elevated": "Elevated",
    "zone.loud": "Loud",
    "zone.danger": "Danger",

    // -- language suggestion banner --
    "banner.text": "This page is also available in your language.",
    "banner.cta": "View in {lang}",
    "banner.dismiss": "Dismiss",

    // -- keyboard help modal --
    "kbd.title": "Keyboard shortcuts",
    "kbd.subtitle": "Navigate and control the meter without touching the mouse.",
    "kbd.close": "Close",
    "kbd.group.meter": "Meter",
    "kbd.group.nav": "Navigation",
    "kbd.group.general": "General",
    "kbd.meter.toggle": "Start / stop measuring",
    "kbd.meter.reset": "Reset statistics",
    "kbd.meter.weight": "Cycle weighting (A / C / Z)",
    "kbd.meter.response": "Toggle Fast / Slow response",
    "kbd.meter.csv": "Export CSV",
    "kbd.nav.hint": "Press g then a key:",
    "kbd.nav.home": "Go to meter (home)",
    "kbd.nav.decibel": "Go to decibel chart",
    "kbd.nav.exposure": "Go to safe-exposure calculator",
    "kbd.nav.classroom": "Go to classroom meter",
    "kbd.nav.blog": "Go to blog",
    "kbd.nav.faq": "Go to FAQ",
    "kbd.general.help": "Show / hide this help",
    "kbd.general.theme": "Toggle light / dark theme",
    "kbd.general.lang": "Open language menu",
    "kbd.general.esc": "Close dialog / menu",

    // -- landing page --
    "home.hero.eyebrow": "Free online sound level meter",
    "home.hero.title": "Measure noise in decibels, right in your browser",
    "home.hero.subtitle":
      "A fast, private sound meter with the metrics professionals expect — dBA, LAeq, frequency weighting and time response. No app, no upload, no sign-up.",
    "home.hero.tip":
      "Tip: allow microphone access when prompted. For the most accurate numbers, set a calibration offset against a known reference.",

    "home.features.eyebrow": "Why this meter",
    "home.features.title": "More than a single number",
    "home.features.intro":
      "Most online meters show one figure and stop. This one gives you the weightings, time response and statistics that real measurement needs — without losing the simplicity.",
    "home.f1.title": "A / C / Z weighting",
    "home.f1.body":
      "Switch between A-weighting for hearing-risk assessment, C for low-frequency and peak noise, or Z for the unweighted spectrum.",
    "home.f2.title": "Fast & Slow response",
    "home.f2.body":
      "Standard IEC 61672 time-weightings — Fast (125 ms) to catch transients, Slow (1 s) for steady, readable levels.",
    "home.f3.title": "LAeq & statistics",
    "home.f3.body":
      "Live Min, Max, energy-average and the equivalent continuous level LAeq — the metric used in noise regulations.",
    "home.f4.title": "Export CSV & PDF",
    "home.f4.body":
      "Download the full level history as CSV, or save a clean summary report as a PDF — generated on your device.",
    "home.f5.title": "Completely private",
    "home.f5.body":
      "Audio is analysed locally with the Web Audio API and discarded instantly. Nothing is recorded, stored, or uploaded.",
    "home.f6.title": "Works on any device",
    "home.f6.body":
      "A pure static site — no install, no sign-up. Open it on a phone, tablet, or laptop and start measuring instantly.",

    "home.scale.eyebrow": "Reference",
    "home.scale.title": "What do the decibel numbers mean?",
    "home.scale.intro":
      "Decibels are logarithmic — every 10 dB increase is roughly a doubling of perceived loudness. Here is how everyday sounds compare.",
    "home.scale.callout.title": "The 85 dB line",
    "home.scale.callout.body":
      "NIOSH sets the recommended exposure limit at 85 dBA over 8 hours. Above it, your safe daily dose halves for every extra 3 dB — so 88 dBA is safe for only 4 hours, and 91 dBA for just 2.",
    "home.scale.link": "See the full decibel chart →",

    "home.health.eyebrow": "Why it matters",
    "home.health.title": "The cost of too much noise",
    "home.health.intro":
      "Noise is not just an annoyance. Sustained exposure has measurable effects on hearing, sleep, stress and concentration.",
    "home.h1.title": "Noise-induced hearing loss",
    "home.h1.body":
      "Sustained exposure above 85 dBA damages the inner ear. The loss is gradual, painless and permanent — which is why monitoring matters before symptoms appear.",
    "home.h2.title": "Stress and cardiovascular strain",
    "home.h2.body":
      "Chronic noise keeps the body in a low-grade stress state, which long-term studies link to higher blood pressure and cardiovascular risk.",
    "home.h3.title": "Sleep disruption",
    "home.h3.body":
      "Night-time noise above roughly 40 dB can fragment sleep even when you do not fully wake. Keep bedroom noise well below this.",
    "home.h4.title": "Concentration and learning",
    "home.h4.body":
      "Background noise competes for attention. In classrooms and offices it measurably reduces comprehension and memory — children most of all.",
    "home.health.note":
      "Informed by guidance from NIOSH, the WHO and the NIDCD.",

    "home.faq.eyebrow": "FAQ",
    "home.faq.title": "Questions about online sound measurement",
    "home.faq.q1": "How accurate is an online sound meter?",
    "home.faq.a1":
      "It depends on your device. Phone and laptop mics are not calibrated instruments, but once you set a calibration offset, expect roughly ±3–5 dB for everyday levels — enough to compare rooms and track trends, not for legal evidence.",
    "home.faq.q2": "Does this record or upload my audio?",
    "home.faq.a2":
      "No. Everything is processed in your browser with the Web Audio API and discarded frame by frame. Nothing is recorded, stored, or sent to a server.",
    "home.faq.q3": "What is the difference between dBA, dBC and dBZ?",
    "home.faq.a3":
      "They are frequency weightings. dBA mimics human hearing (the standard for hearing-risk), dBC captures more bass, and dBZ is the raw, unweighted spectrum.",
    "home.faq.q4": "What sound level is dangerous?",
    "home.faq.a4":
      "Prolonged exposure at or above 85 dBA can cause permanent hearing loss, and the safe daily dose halves for every extra 3 dB. Sounds at 120 dB and above can cause immediate harm.",
    "home.faq.more": "More in our full FAQ.",

    "home.cta.title": "Ready to check your noise levels?",
    "home.cta.body":
      "Scroll back up and press start, or explore the decibel chart and exposure calculator to learn what your numbers mean.",
    "home.cta.measure": "Start measuring",
    "home.cta.chart": "Decibel chart",
  },

  // ===========================================================================
  // 中文 (简体) — Chinese (Simplified)
  // ===========================================================================
  zh: {
    "common.skip": "跳到主要内容",
    "common.start": "开始测量",
    "common.home": "首页",
    "common.language": "语言",
    "common.theme": "切换浅色 / 深色",
    "common.menu.open": "打开菜单",
    "common.menu.close": "关闭菜单",
    "common.keyboard": "键盘快捷键",

    "nav.meter": "声级计",
    "nav.decibelChart": "分贝对照表",
    "nav.safeExposure": "安全暴露",
    "nav.classroom": "教室噪音",
    "nav.blog": "博客",
    "nav.faq": "常见问题",
    "nav.howItWorks": "工作原理",
    "nav.accuracy": "精度与校准",
    "nav.about": "关于",
    "nav.methodology": "方法说明",
    "nav.privacy": "隐私",

    "footer.tools": "工具",
    "footer.learn": "了解",
    "footer.about": "关于",
    "footer.tagline":
      "一款免费、私密的声级计，完全在您的浏览器中运行。音频绝不会离开您的设备。",
    "footer.rights": "所有读数均为参考估计值。",
    "footer.sources": "为精确而打造 · 资料来源",

    "meter.aria": "实时声级计",
    "meter.idle": "麦克风空闲",
    "meter.measuring": "测量中…",
    "meter.unavailable": "不可用",
    "meter.weight": "计权",
    "meter.fast": "快",
    "meter.slow": "慢",
    "meter.idleZone": "空闲",
    "meter.min": "最小",
    "meter.max": "最大",
    "meter.avg": "平均",
    "meter.leq": "LAeq",
    "meter.spectrum": "频谱",
    "meter.spectrumHint": "开始测量以查看实时频谱",
    "meter.history": "声级历史 · 最近 60 秒",
    "meter.nioshLimit": "NIOSH 85 dB 限值",
    "meter.stop": "停止",
    "meter.reset": "重置",
    "meter.calibrate": "校准",
    "meter.exportCsv": "导出 CSV",
    "meter.savePdf": "保存 PDF",
    "meter.note":
      "音频在本地处理，绝不会离开您的设备。手机或笔记本麦克风并非校准过的声级计——读数仅为参考估计值。请使用校准偏移量对齐已知参考。",
    "meter.errUnsupported": "此浏览器不支持麦克风访问。",
    "meter.errDenied":
      "麦克风权限被拒绝。请允许访问并重新加载以进行测量。音频仅保留在您的设备上。",
    "meter.srSummary": "{db} 分贝，{zone}。平均 {avg}，最大 {max}。",
    "meter.report.title": "声级报告",
    "meter.report.average": "平均值",
    "meter.report.metric": "指标",
    "meter.report.value": "数值",
    "meter.report.note":
      "由 Online Sound Meter 生成。读数为消费级麦克风未经校准的参考估计值，不能替代 1/2 级声级计。资料来源：NIOSH、WHO、NIDCD。",

    "zone.quiet": "安静",
    "zone.moderate": "适中",
    "zone.elevated": "偏高",
    "zone.loud": "吵闹",
    "zone.danger": "危险",

    "banner.text": "本页面也提供您的语言版本。",
    "banner.cta": "查看 {lang} 版本",
    "banner.dismiss": "忽略",

    "kbd.title": "键盘快捷键",
    "kbd.subtitle": "无需鼠标即可浏览并控制声级计。",
    "kbd.close": "关闭",
    "kbd.group.meter": "声级计",
    "kbd.group.nav": "导航",
    "kbd.group.general": "通用",
    "kbd.meter.toggle": "开始 / 停止测量",
    "kbd.meter.reset": "重置统计",
    "kbd.meter.weight": "切换计权 (A / C / Z)",
    "kbd.meter.response": "切换快 / 慢响应",
    "kbd.meter.csv": "导出 CSV",
    "kbd.nav.hint": "先按 g 再按一个键：",
    "kbd.nav.home": "前往声级计（首页）",
    "kbd.nav.decibel": "前往分贝对照表",
    "kbd.nav.exposure": "前往安全暴露计算器",
    "kbd.nav.classroom": "前往教室声级计",
    "kbd.nav.blog": "前往博客",
    "kbd.nav.faq": "前往常见问题",
    "kbd.general.help": "显示 / 隐藏此帮助",
    "kbd.general.theme": "切换浅色 / 深色主题",
    "kbd.general.lang": "打开语言菜单",
    "kbd.general.esc": "关闭对话框 / 菜单",

    "home.hero.eyebrow": "免费在线声级计",
    "home.hero.title": "在浏览器中直接测量噪音分贝",
    "home.hero.subtitle":
      "一款快速、私密的声级计，具备专业人士期待的指标——dBA、LAeq、频率计权与时间响应。无需应用、无需上传、无需注册。",
    "home.hero.tip":
      "提示：在提示时允许麦克风访问。为获得最准确的数值，请相对已知参考设置校准偏移量。",

    "home.features.eyebrow": "为什么选它",
    "home.features.title": "不止一个数字",
    "home.features.intro":
      "大多数在线声级计只显示一个数字便止步于此。本工具为您提供真实测量所需的计权、时间响应与统计数据——同时保持简单易用。",
    "home.f1.title": "A / C / Z 计权",
    "home.f1.body":
      "在用于听力风险评估的 A 计权、用于低频与峰值噪音的 C 计权，以及未计权频谱的 Z 之间切换。",
    "home.f2.title": "快与慢响应",
    "home.f2.body":
      "标准 IEC 61672 时间计权——快 (125 毫秒) 捕捉瞬态，慢 (1 秒) 提供平稳易读的声级。",
    "home.f3.title": "LAeq 与统计",
    "home.f3.body":
      "实时显示最小值、最大值、能量平均及等效连续声级 LAeq——噪音法规所采用的指标。",
    "home.f4.title": "导出 CSV 与 PDF",
    "home.f4.body":
      "将完整声级历史下载为 CSV，或保存为简洁的 PDF 摘要报告——均在您的设备上生成。",
    "home.f5.title": "完全私密",
    "home.f5.body":
      "音频通过 Web Audio API 在本地分析并立即丢弃。绝不录制、存储或上传任何内容。",
    "home.f6.title": "适用于任何设备",
    "home.f6.body":
      "纯静态网站——无需安装、无需注册。在手机、平板或笔记本上打开即可立即测量。",

    "home.scale.eyebrow": "参考",
    "home.scale.title": "分贝数字意味着什么？",
    "home.scale.intro":
      "分贝是对数刻度——每增加 10 dB，感知响度大约翻倍。以下是日常声音的对比。",
    "home.scale.callout.title": "85 dB 这条线",
    "home.scale.callout.body":
      "NIOSH 将推荐暴露限值定为 8 小时内 85 dBA。超过此值后，每多 3 dB，每日安全剂量便减半——因此 88 dBA 仅安全 4 小时，91 dBA 仅 2 小时。",
    "home.scale.link": "查看完整分贝对照表 →",

    "home.health.eyebrow": "为何重要",
    "home.health.title": "噪音过度的代价",
    "home.health.intro":
      "噪音不仅是一种烦扰。持续暴露对听力、睡眠、压力与注意力都有可衡量的影响。",
    "home.h1.title": "噪声性听力损失",
    "home.h1.body":
      "持续暴露在 85 dBA 以上会损伤内耳。这种损失是渐进、无痛且不可逆的——正因如此，应在症状出现前进行监测。",
    "home.h2.title": "压力与心血管负担",
    "home.h2.body":
      "长期噪音使身体处于低度应激状态，长期研究将其与更高的血压和心血管风险联系起来。",
    "home.h3.title": "睡眠干扰",
    "home.h3.body":
      "夜间噪音超过约 40 dB 即可打断睡眠，即使您并未完全醒来。请将卧室噪音保持在远低于此的水平。",
    "home.h4.title": "注意力与学习",
    "home.h4.body":
      "背景噪音会争夺注意力。在教室和办公室中，它会明显降低理解力与记忆力——儿童受影响最大。",
    "home.health.note": "参考 NIOSH、WHO 与 NIDCD 的指南。",

    "home.faq.eyebrow": "常见问题",
    "home.faq.title": "关于在线声音测量的问题",
    "home.faq.q1": "在线声级计有多准确？",
    "home.faq.a1":
      "取决于您的设备。手机和笔记本麦克风并非校准仪器，但设置校准偏移后，日常声级大约可达 ±3–5 dB——足以比较房间和追踪趋势，但不能作为法律证据。",
    "home.faq.q2": "它会录制或上传我的音频吗？",
    "home.faq.a2":
      "不会。一切都通过 Web Audio API 在您的浏览器中处理并逐帧丢弃。绝不录制、存储或发送到服务器。",
    "home.faq.q3": "dBA、dBC 和 dBZ 有什么区别？",
    "home.faq.a3":
      "它们是频率计权。dBA 模拟人耳听觉（听力风险的标准），dBC 捕捉更多低频，dBZ 则是原始的未计权频谱。",
    "home.faq.q4": "多大的声级是危险的？",
    "home.faq.a4":
      "长期暴露在 85 dBA 或以上会造成永久性听力损失，且每多 3 dB，每日安全剂量便减半。120 dB 及以上的声音可造成即时伤害。",
    "home.faq.more": "更多内容见完整常见问题。",

    "home.cta.title": "准备好检查您的噪音水平了吗？",
    "home.cta.body":
      "向上滚动并按开始，或浏览分贝对照表与暴露计算器，了解您的数字意味着什么。",
    "home.cta.measure": "开始测量",
    "home.cta.chart": "分贝对照表",
  },

  // ===========================================================================
  // Español — Spanish
  // ===========================================================================
  es: {
    "common.skip": "Saltar al contenido",
    "common.start": "Empezar a medir",
    "common.home": "Inicio",
    "common.language": "Idioma",
    "common.theme": "Cambiar claro / oscuro",
    "common.menu.open": "Abrir menú",
    "common.menu.close": "Cerrar menú",
    "common.keyboard": "Atajos de teclado",

    "nav.meter": "Medidor",
    "nav.decibelChart": "Tabla de decibelios",
    "nav.safeExposure": "Exposición segura",
    "nav.classroom": "Aula",
    "nav.blog": "Blog",
    "nav.faq": "Preguntas frecuentes",
    "nav.howItWorks": "Cómo funciona",
    "nav.accuracy": "Precisión y calibración",
    "nav.about": "Acerca de",
    "nav.methodology": "Metodología",
    "nav.privacy": "Privacidad",

    "footer.tools": "Herramientas",
    "footer.learn": "Aprender",
    "footer.about": "Acerca de",
    "footer.tagline":
      "Un sonómetro gratuito y privado que funciona por completo en tu navegador. El audio nunca sale de tu dispositivo.",
    "footer.rights": "Todas las lecturas son estimaciones de referencia.",
    "footer.sources": "Hecho con precisión · Fuentes",

    "meter.aria": "Sonómetro en vivo",
    "meter.idle": "Micrófono inactivo",
    "meter.measuring": "Midiendo…",
    "meter.unavailable": "No disponible",
    "meter.weight": "Pond.",
    "meter.fast": "Rápido",
    "meter.slow": "Lento",
    "meter.idleZone": "Inactivo",
    "meter.min": "Mín",
    "meter.max": "Máx",
    "meter.avg": "Prom",
    "meter.leq": "LAeq",
    "meter.spectrum": "Espectro de frecuencia",
    "meter.spectrumHint": "Empieza a medir para ver el espectro en vivo",
    "meter.history": "Historial de nivel · últimos 60 s",
    "meter.nioshLimit": "Límite NIOSH 85 dB",
    "meter.stop": "Detener",
    "meter.reset": "Reiniciar",
    "meter.calibrate": "Calibrar",
    "meter.exportCsv": "Exportar CSV",
    "meter.savePdf": "Guardar PDF",
    "meter.note":
      "El audio se procesa localmente y nunca sale de tu dispositivo. El micrófono de un teléfono o portátil no es un sonómetro calibrado: las lecturas son estimaciones de referencia. Usa el ajuste de calibración para alinearlo con una referencia conocida.",
    "meter.errUnsupported": "Este navegador no admite el acceso al micrófono.",
    "meter.errDenied":
      "Permiso de micrófono denegado. Permite el acceso y recarga para medir. El audio permanece en tu dispositivo.",
    "meter.srSummary": "{db} decibelios, {zone}. Promedio {avg}, máximo {max}.",
    "meter.report.title": "Informe de nivel sonoro",
    "meter.report.average": "promedio",
    "meter.report.metric": "Métrica",
    "meter.report.value": "Valor",
    "meter.report.note":
      "Generado por Online Sound Meter. Las lecturas son estimaciones de referencia sin calibrar de un micrófono de consumo, no un sustituto de un sonómetro de Tipo 1/2. Fuentes: NIOSH, WHO, NIDCD.",

    "zone.quiet": "Silencioso",
    "zone.moderate": "Moderado",
    "zone.elevated": "Elevado",
    "zone.loud": "Ruidoso",
    "zone.danger": "Peligro",

    "banner.text": "Esta página también está disponible en tu idioma.",
    "banner.cta": "Ver en {lang}",
    "banner.dismiss": "Descartar",

    "kbd.title": "Atajos de teclado",
    "kbd.subtitle": "Navega y controla el medidor sin tocar el ratón.",
    "kbd.close": "Cerrar",
    "kbd.group.meter": "Medidor",
    "kbd.group.nav": "Navegación",
    "kbd.group.general": "General",
    "kbd.meter.toggle": "Iniciar / detener medición",
    "kbd.meter.reset": "Reiniciar estadísticas",
    "kbd.meter.weight": "Cambiar ponderación (A / C / Z)",
    "kbd.meter.response": "Alternar respuesta rápida / lenta",
    "kbd.meter.csv": "Exportar CSV",
    "kbd.nav.hint": "Pulsa g y luego una tecla:",
    "kbd.nav.home": "Ir al medidor (inicio)",
    "kbd.nav.decibel": "Ir a la tabla de decibelios",
    "kbd.nav.exposure": "Ir a la calculadora de exposición segura",
    "kbd.nav.classroom": "Ir al medidor de aula",
    "kbd.nav.blog": "Ir al blog",
    "kbd.nav.faq": "Ir a preguntas frecuentes",
    "kbd.general.help": "Mostrar / ocultar esta ayuda",
    "kbd.general.theme": "Cambiar tema claro / oscuro",
    "kbd.general.lang": "Abrir el menú de idioma",
    "kbd.general.esc": "Cerrar diálogo / menú",

    "home.hero.eyebrow": "Sonómetro en línea gratuito",
    "home.hero.title": "Mide el ruido en decibelios, en tu navegador",
    "home.hero.subtitle":
      "Un sonómetro rápido y privado con las métricas que esperan los profesionales: dBA, LAeq, ponderación de frecuencia y respuesta temporal. Sin app, sin subir nada, sin registro.",
    "home.hero.tip":
      "Consejo: permite el acceso al micrófono cuando se solicite. Para los valores más precisos, define un ajuste de calibración frente a una referencia conocida.",

    "home.features.eyebrow": "Por qué este medidor",
    "home.features.title": "Más que un solo número",
    "home.features.intro":
      "La mayoría de los medidores en línea muestran una cifra y ya. Este te da las ponderaciones, la respuesta temporal y las estadísticas que necesita una medición real, sin perder la simplicidad.",
    "home.f1.title": "Ponderación A / C / Z",
    "home.f1.body":
      "Cambia entre la ponderación A para el riesgo auditivo, C para ruido de baja frecuencia y picos, o Z para el espectro sin ponderar.",
    "home.f2.title": "Respuesta rápida y lenta",
    "home.f2.body":
      "Ponderaciones temporales estándar IEC 61672: Rápida (125 ms) para captar transitorios, Lenta (1 s) para niveles estables y legibles.",
    "home.f3.title": "LAeq y estadísticas",
    "home.f3.body":
      "Mín, Máx, promedio de energía y el nivel continuo equivalente LAeq en vivo: la métrica usada en la normativa de ruido.",
    "home.f4.title": "Exportar CSV y PDF",
    "home.f4.body":
      "Descarga todo el historial de nivel como CSV, o guarda un informe resumido en PDF, generado en tu dispositivo.",
    "home.f5.title": "Totalmente privado",
    "home.f5.body":
      "El audio se analiza localmente con la Web Audio API y se descarta al instante. Nada se graba, almacena ni sube.",
    "home.f6.title": "Funciona en cualquier dispositivo",
    "home.f6.body":
      "Un sitio puramente estático: sin instalación, sin registro. Ábrelo en un teléfono, tableta o portátil y empieza a medir al instante.",

    "home.scale.eyebrow": "Referencia",
    "home.scale.title": "¿Qué significan los números de decibelios?",
    "home.scale.intro":
      "Los decibelios son logarítmicos: cada aumento de 10 dB duplica aproximadamente la sonoridad percibida. Así se comparan los sonidos cotidianos.",
    "home.scale.callout.title": "La línea de los 85 dB",
    "home.scale.callout.body":
      "NIOSH fija el límite de exposición recomendado en 85 dBA durante 8 horas. Por encima, tu dosis diaria segura se reduce a la mitad por cada 3 dB extra: 88 dBA es seguro solo 4 horas, y 91 dBA apenas 2.",
    "home.scale.link": "Ver la tabla completa de decibelios →",

    "home.health.eyebrow": "Por qué importa",
    "home.health.title": "El precio de demasiado ruido",
    "home.health.intro":
      "El ruido no es solo una molestia. La exposición sostenida tiene efectos medibles en la audición, el sueño, el estrés y la concentración.",
    "home.h1.title": "Pérdida auditiva por ruido",
    "home.h1.body":
      "La exposición sostenida por encima de 85 dBA daña el oído interno. La pérdida es gradual, indolora y permanente, por eso importa medir antes de que aparezcan los síntomas.",
    "home.h2.title": "Estrés y carga cardiovascular",
    "home.h2.body":
      "El ruido crónico mantiene al cuerpo en un estado de estrés leve, que los estudios a largo plazo vinculan con mayor presión arterial y riesgo cardiovascular.",
    "home.h3.title": "Alteración del sueño",
    "home.h3.body":
      "El ruido nocturno por encima de unos 40 dB puede fragmentar el sueño aunque no llegues a despertarte. Mantén el ruido del dormitorio muy por debajo de eso.",
    "home.h4.title": "Concentración y aprendizaje",
    "home.h4.body":
      "El ruido de fondo compite por la atención. En aulas y oficinas reduce de forma medible la comprensión y la memoria, sobre todo en los niños.",
    "home.health.note": "Basado en las pautas de NIOSH, la OMS y el NIDCD.",

    "home.faq.eyebrow": "Preguntas frecuentes",
    "home.faq.title": "Preguntas sobre la medición de sonido en línea",
    "home.faq.q1": "¿Qué precisión tiene un sonómetro en línea?",
    "home.faq.a1":
      "Depende de tu dispositivo. Los micrófonos de teléfonos y portátiles no son instrumentos calibrados, pero con un ajuste de calibración puedes esperar unos ±3–5 dB en niveles cotidianos: suficiente para comparar salas y seguir tendencias, no como prueba legal.",
    "home.faq.q2": "¿Graba o sube mi audio?",
    "home.faq.a2":
      "No. Todo se procesa en tu navegador con la Web Audio API y se descarta fotograma a fotograma. Nada se graba, almacena ni envía a un servidor.",
    "home.faq.q3": "¿Cuál es la diferencia entre dBA, dBC y dBZ?",
    "home.faq.a3":
      "Son ponderaciones de frecuencia. dBA imita el oído humano (el estándar para el riesgo auditivo), dBC capta más graves y dBZ es el espectro bruto, sin ponderar.",
    "home.faq.q4": "¿Qué nivel de sonido es peligroso?",
    "home.faq.a4":
      "La exposición prolongada a 85 dBA o más puede causar pérdida auditiva permanente, y la dosis diaria segura se reduce a la mitad por cada 3 dB extra. Los sonidos de 120 dB o más pueden causar daño inmediato.",
    "home.faq.more": "Más en nuestras preguntas frecuentes completas.",

    "home.cta.title": "¿Listo para comprobar tus niveles de ruido?",
    "home.cta.body":
      "Vuelve arriba y pulsa empezar, o explora la tabla de decibelios y la calculadora de exposición para entender qué significan tus números.",
    "home.cta.measure": "Empezar a medir",
    "home.cta.chart": "Tabla de decibelios",
  },

  // ===========================================================================
  // Deutsch — German
  // ===========================================================================
  de: {
    "common.skip": "Zum Inhalt springen",
    "common.start": "Messung starten",
    "common.home": "Start",
    "common.language": "Sprache",
    "common.theme": "Hell / Dunkel umschalten",
    "common.menu.open": "Menü öffnen",
    "common.menu.close": "Menü schließen",
    "common.keyboard": "Tastenkürzel",

    "nav.meter": "Messgerät",
    "nav.decibelChart": "Dezibel-Tabelle",
    "nav.safeExposure": "Sichere Belastung",
    "nav.classroom": "Klassenzimmer",
    "nav.blog": "Blog",
    "nav.faq": "FAQ",
    "nav.howItWorks": "Funktionsweise",
    "nav.accuracy": "Genauigkeit & Kalibrierung",
    "nav.about": "Über uns",
    "nav.methodology": "Methodik",
    "nav.privacy": "Datenschutz",

    "footer.tools": "Werkzeuge",
    "footer.learn": "Lernen",
    "footer.about": "Über uns",
    "footer.tagline":
      "Ein kostenloses, privates Schallpegelmessgerät, das vollständig im Browser läuft. Audio verlässt nie Ihr Gerät.",
    "footer.rights": "Alle Messwerte sind Referenzschätzungen.",
    "footer.sources": "Auf Genauigkeit ausgelegt · Quellen",

    "meter.aria": "Live-Schallpegelmesser",
    "meter.idle": "Mikrofon inaktiv",
    "meter.measuring": "Messung…",
    "meter.unavailable": "Nicht verfügbar",
    "meter.weight": "Bew.",
    "meter.fast": "Schnell",
    "meter.slow": "Langsam",
    "meter.idleZone": "Inaktiv",
    "meter.min": "Min",
    "meter.max": "Max",
    "meter.avg": "Mittel",
    "meter.leq": "LAeq",
    "meter.spectrum": "Frequenzspektrum",
    "meter.spectrumHint": "Messung starten, um das Live-Spektrum zu sehen",
    "meter.history": "Pegelverlauf · letzte 60 s",
    "meter.nioshLimit": "NIOSH 85-dB-Grenze",
    "meter.stop": "Stopp",
    "meter.reset": "Zurücksetzen",
    "meter.calibrate": "Kalibrieren",
    "meter.exportCsv": "CSV exportieren",
    "meter.savePdf": "PDF speichern",
    "meter.note":
      "Audio wird lokal verarbeitet und verlässt nie Ihr Gerät. Ein Handy- oder Laptop-Mikrofon ist kein kalibriertes Messgerät – die Werte sind Referenzschätzungen. Nutzen Sie den Kalibrierungs-Offset, um es an eine bekannte Referenz anzugleichen.",
    "meter.errUnsupported": "Dieser Browser unterstützt keinen Mikrofonzugriff.",
    "meter.errDenied":
      "Mikrofonzugriff verweigert. Erlauben Sie den Zugriff und laden Sie neu, um zu messen. Audio bleibt auf Ihrem Gerät.",
    "meter.srSummary": "{db} Dezibel, {zone}. Mittel {avg}, Max {max}.",
    "meter.report.title": "Schallpegel-Bericht",
    "meter.report.average": "Durchschnitt",
    "meter.report.metric": "Kennwert",
    "meter.report.value": "Wert",
    "meter.report.note":
      "Erstellt mit Online Sound Meter. Die Werte sind unkalibrierte Referenzschätzungen eines Consumer-Mikrofons, kein Ersatz für ein Schallpegelmessgerät der Klasse 1/2. Quellen: NIOSH, WHO, NIDCD.",

    "zone.quiet": "Leise",
    "zone.moderate": "Mäßig",
    "zone.elevated": "Erhöht",
    "zone.loud": "Laut",
    "zone.danger": "Gefahr",

    "banner.text": "Diese Seite ist auch in Ihrer Sprache verfügbar.",
    "banner.cta": "Auf {lang} ansehen",
    "banner.dismiss": "Schließen",

    "kbd.title": "Tastenkürzel",
    "kbd.subtitle": "Navigieren und das Messgerät steuern – ganz ohne Maus.",
    "kbd.close": "Schließen",
    "kbd.group.meter": "Messgerät",
    "kbd.group.nav": "Navigation",
    "kbd.group.general": "Allgemein",
    "kbd.meter.toggle": "Messung starten / stoppen",
    "kbd.meter.reset": "Statistik zurücksetzen",
    "kbd.meter.weight": "Bewertung wechseln (A / C / Z)",
    "kbd.meter.response": "Schnell / Langsam umschalten",
    "kbd.meter.csv": "CSV exportieren",
    "kbd.nav.hint": "Drücken Sie g, dann eine Taste:",
    "kbd.nav.home": "Zum Messgerät (Start)",
    "kbd.nav.decibel": "Zur Dezibel-Tabelle",
    "kbd.nav.exposure": "Zum Rechner für sichere Belastung",
    "kbd.nav.classroom": "Zum Klassenzimmer-Messgerät",
    "kbd.nav.blog": "Zum Blog",
    "kbd.nav.faq": "Zu den FAQ",
    "kbd.general.help": "Diese Hilfe ein-/ausblenden",
    "kbd.general.theme": "Helles / dunkles Design umschalten",
    "kbd.general.lang": "Sprachmenü öffnen",
    "kbd.general.esc": "Dialog / Menü schließen",

    "home.hero.eyebrow": "Kostenloser Online-Schallpegelmesser",
    "home.hero.title": "Messen Sie Lärm in Dezibel – direkt im Browser",
    "home.hero.subtitle":
      "Ein schneller, privater Schallpegelmesser mit den Kennwerten, die Profis erwarten – dBA, LAeq, Frequenzbewertung und Zeitverhalten. Keine App, kein Upload, keine Anmeldung.",
    "home.hero.tip":
      "Tipp: Erlauben Sie den Mikrofonzugriff, wenn Sie gefragt werden. Für möglichst genaue Werte setzen Sie einen Kalibrierungs-Offset gegenüber einer bekannten Referenz.",

    "home.features.eyebrow": "Warum dieses Messgerät",
    "home.features.title": "Mehr als nur eine Zahl",
    "home.features.intro":
      "Die meisten Online-Messgeräte zeigen einen Wert und das war's. Dieses liefert die Bewertungen, das Zeitverhalten und die Statistik, die eine echte Messung braucht – ohne die Einfachheit zu verlieren.",
    "home.f1.title": "A- / C- / Z-Bewertung",
    "home.f1.body":
      "Wechseln Sie zwischen A-Bewertung für die Gehörgefährdung, C für tieffrequenten und Spitzenlärm oder Z für das unbewertete Spektrum.",
    "home.f2.title": "Schnelles & langsames Zeitverhalten",
    "home.f2.body":
      "Standard-Zeitbewertungen nach IEC 61672 – Schnell (125 ms) für Transienten, Langsam (1 s) für ruhige, ablesbare Pegel.",
    "home.f3.title": "LAeq & Statistik",
    "home.f3.body":
      "Live Min, Max, Energiemittel und der äquivalente Dauerschallpegel LAeq – der Kennwert aus den Lärmvorschriften.",
    "home.f4.title": "CSV & PDF exportieren",
    "home.f4.body":
      "Laden Sie den gesamten Pegelverlauf als CSV herunter oder speichern Sie einen sauberen PDF-Bericht – auf Ihrem Gerät erzeugt.",
    "home.f5.title": "Völlig privat",
    "home.f5.body":
      "Audio wird lokal mit der Web Audio API analysiert und sofort verworfen. Nichts wird aufgezeichnet, gespeichert oder hochgeladen.",
    "home.f6.title": "Läuft auf jedem Gerät",
    "home.f6.body":
      "Eine rein statische Website – keine Installation, keine Anmeldung. Auf Handy, Tablet oder Laptop öffnen und sofort messen.",

    "home.scale.eyebrow": "Referenz",
    "home.scale.title": "Was bedeuten die Dezibel-Zahlen?",
    "home.scale.intro":
      "Dezibel sind logarithmisch – jede Zunahme um 10 dB verdoppelt etwa die empfundene Lautstärke. So vergleichen sich Alltagsgeräusche.",
    "home.scale.callout.title": "Die 85-dB-Linie",
    "home.scale.callout.body":
      "NIOSH legt den empfohlenen Belastungsgrenzwert auf 85 dBA über 8 Stunden fest. Darüber halbiert sich Ihre sichere Tagesdosis mit jeden weiteren 3 dB – 88 dBA sind nur 4 Stunden sicher, 91 dBA nur 2.",
    "home.scale.link": "Vollständige Dezibel-Tabelle ansehen →",

    "home.health.eyebrow": "Warum es zählt",
    "home.health.title": "Der Preis von zu viel Lärm",
    "home.health.intro":
      "Lärm ist nicht nur lästig. Anhaltende Belastung hat messbare Folgen für Gehör, Schlaf, Stress und Konzentration.",
    "home.h1.title": "Lärmbedingter Hörverlust",
    "home.h1.body":
      "Anhaltende Belastung über 85 dBA schädigt das Innenohr. Der Verlust ist allmählich, schmerzlos und dauerhaft – deshalb zählt das Messen, bevor Symptome auftreten.",
    "home.h2.title": "Stress und Herz-Kreislauf-Belastung",
    "home.h2.body":
      "Chronischer Lärm hält den Körper in leichtem Stress, was Langzeitstudien mit höherem Blutdruck und Herz-Kreislauf-Risiko verbinden.",
    "home.h3.title": "Schlafstörung",
    "home.h3.body":
      "Nächtlicher Lärm über etwa 40 dB kann den Schlaf fragmentieren, auch wenn Sie nicht ganz aufwachen. Halten Sie den Schlafzimmerlärm deutlich darunter.",
    "home.h4.title": "Konzentration und Lernen",
    "home.h4.body":
      "Hintergrundlärm konkurriert um Aufmerksamkeit. In Klassenzimmern und Büros senkt er messbar Verständnis und Gedächtnis – Kinder am stärksten.",
    "home.health.note": "Auf Basis der Leitlinien von NIOSH, WHO und NIDCD.",

    "home.faq.eyebrow": "FAQ",
    "home.faq.title": "Fragen zur Online-Schallmessung",
    "home.faq.q1": "Wie genau ist ein Online-Schallpegelmesser?",
    "home.faq.a1":
      "Das hängt von Ihrem Gerät ab. Handy- und Laptop-Mikrofone sind keine kalibrierten Instrumente, aber mit einem Kalibrierungs-Offset sind etwa ±3–5 dB bei Alltagspegeln realistisch – genug, um Räume zu vergleichen und Trends zu verfolgen, nicht als rechtlicher Nachweis.",
    "home.faq.q2": "Wird mein Audio aufgezeichnet oder hochgeladen?",
    "home.faq.a2":
      "Nein. Alles wird im Browser mit der Web Audio API verarbeitet und Bild für Bild verworfen. Nichts wird aufgezeichnet, gespeichert oder an einen Server gesendet.",
    "home.faq.q3": "Was ist der Unterschied zwischen dBA, dBC und dBZ?",
    "home.faq.a3":
      "Es sind Frequenzbewertungen. dBA bildet das menschliche Gehör nach (der Standard für Gehörgefährdung), dBC erfasst mehr Bass und dBZ ist das rohe, unbewertete Spektrum.",
    "home.faq.q4": "Welcher Schallpegel ist gefährlich?",
    "home.faq.a4":
      "Längere Belastung ab 85 dBA kann dauerhaften Hörverlust verursachen, und die sichere Tagesdosis halbiert sich mit jeden weiteren 3 dB. Geräusche ab 120 dB können sofort schaden.",
    "home.faq.more": "Mehr in unseren vollständigen FAQ.",

    "home.cta.title": "Bereit, Ihre Lärmpegel zu prüfen?",
    "home.cta.body":
      "Scrollen Sie nach oben und drücken Sie Start, oder erkunden Sie die Dezibel-Tabelle und den Belastungsrechner, um Ihre Zahlen zu verstehen.",
    "home.cta.measure": "Messung starten",
    "home.cta.chart": "Dezibel-Tabelle",
  },

  // ===========================================================================
  // 日本語 — Japanese
  // ===========================================================================
  ja: {
    "common.skip": "本文へスキップ",
    "common.start": "測定を開始",
    "common.home": "ホーム",
    "common.language": "言語",
    "common.theme": "ライト / ダーク切替",
    "common.menu.open": "メニューを開く",
    "common.menu.close": "メニューを閉じる",
    "common.keyboard": "キーボードショートカット",

    "nav.meter": "騒音計",
    "nav.decibelChart": "デシベル表",
    "nav.safeExposure": "安全な暴露",
    "nav.classroom": "教室",
    "nav.blog": "ブログ",
    "nav.faq": "よくある質問",
    "nav.howItWorks": "仕組み",
    "nav.accuracy": "精度と校正",
    "nav.about": "概要",
    "nav.methodology": "測定方法",
    "nav.privacy": "プライバシー",

    "footer.tools": "ツール",
    "footer.learn": "学ぶ",
    "footer.about": "概要",
    "footer.tagline":
      "ブラウザ内で完結する、無料でプライベートな騒音計。音声がデバイスから外に出ることはありません。",
    "footer.rights": "すべての測定値は参考値です。",
    "footer.sources": "正確さを追求 · 出典",

    "meter.aria": "リアルタイム騒音計",
    "meter.idle": "マイク待機中",
    "meter.measuring": "測定中…",
    "meter.unavailable": "利用不可",
    "meter.weight": "重み付け",
    "meter.fast": "速い",
    "meter.slow": "遅い",
    "meter.idleZone": "待機",
    "meter.min": "最小",
    "meter.max": "最大",
    "meter.avg": "平均",
    "meter.leq": "LAeq",
    "meter.spectrum": "周波数スペクトル",
    "meter.spectrumHint": "測定を開始するとスペクトルが表示されます",
    "meter.history": "レベル履歴 · 直近60秒",
    "meter.nioshLimit": "NIOSH 85 dB 上限",
    "meter.stop": "停止",
    "meter.reset": "リセット",
    "meter.calibrate": "校正",
    "meter.exportCsv": "CSVを書き出す",
    "meter.savePdf": "PDFを保存",
    "meter.note":
      "音声はローカルで処理され、デバイスから外に出ることはありません。スマホやノートPCのマイクは校正された計測器ではないため、測定値は参考値です。既知の基準に合わせるには校正オフセットを使用してください。",
    "meter.errUnsupported": "このブラウザはマイクへのアクセスに対応していません。",
    "meter.errDenied":
      "マイクの許可が拒否されました。アクセスを許可して再読み込みしてください。音声はデバイス内に留まります。",
    "meter.srSummary": "{db} デシベル、{zone}。平均 {avg}、最大 {max}。",
    "meter.report.title": "騒音レベルレポート",
    "meter.report.average": "平均",
    "meter.report.metric": "指標",
    "meter.report.value": "値",
    "meter.report.note":
      "Online Sound Meter により生成。測定値は民生用マイクによる未校正の参考値であり、クラス1/2の騒音計の代わりにはなりません。出典：NIOSH、WHO、NIDCD。",

    "zone.quiet": "静か",
    "zone.moderate": "中程度",
    "zone.elevated": "やや高い",
    "zone.loud": "うるさい",
    "zone.danger": "危険",

    "banner.text": "このページはお使いの言語でもご覧いただけます。",
    "banner.cta": "{lang} で表示",
    "banner.dismiss": "閉じる",

    "kbd.title": "キーボードショートカット",
    "kbd.subtitle": "マウスを使わずに操作・移動できます。",
    "kbd.close": "閉じる",
    "kbd.group.meter": "騒音計",
    "kbd.group.nav": "ナビゲーション",
    "kbd.group.general": "全般",
    "kbd.meter.toggle": "測定の開始 / 停止",
    "kbd.meter.reset": "統計をリセット",
    "kbd.meter.weight": "重み付けを切替 (A / C / Z)",
    "kbd.meter.response": "速い / 遅いを切替",
    "kbd.meter.csv": "CSVを書き出す",
    "kbd.nav.hint": "g を押してからキーを押す：",
    "kbd.nav.home": "騒音計（ホーム）へ",
    "kbd.nav.decibel": "デシベル表へ",
    "kbd.nav.exposure": "安全暴露計算ツールへ",
    "kbd.nav.classroom": "教室用騒音計へ",
    "kbd.nav.blog": "ブログへ",
    "kbd.nav.faq": "よくある質問へ",
    "kbd.general.help": "このヘルプを表示 / 非表示",
    "kbd.general.theme": "ライト / ダークテーマを切替",
    "kbd.general.lang": "言語メニューを開く",
    "kbd.general.esc": "ダイアログ / メニューを閉じる",

    "home.hero.eyebrow": "無料オンライン騒音計",
    "home.hero.title": "ブラウザでそのまま騒音をデシベルで測定",
    "home.hero.subtitle":
      "プロが求める指標を備えた、高速でプライベートな騒音計 — dBA、LAeq、周波数重み付け、時間応答。アプリ不要、アップロード不要、登録不要。",
    "home.hero.tip":
      "ヒント：求められたらマイクへのアクセスを許可してください。最も正確な値を得るには、既知の基準に対して校正オフセットを設定します。",

    "home.features.eyebrow": "この騒音計の特長",
    "home.features.title": "ただの数字以上",
    "home.features.intro":
      "多くのオンライン騒音計は値を1つ表示して終わりです。本ツールは、本格的な測定に必要な重み付け・時間応答・統計を、わかりやすさを損なわずに提供します。",
    "home.f1.title": "A / C / Z 重み付け",
    "home.f1.body":
      "聴覚リスク評価のA特性、低周波やピーク騒音のC特性、重み付けなしのZ特性を切り替えられます。",
    "home.f2.title": "速い・遅い応答",
    "home.f2.body":
      "標準のIEC 61672時間重み付け — 速い(125ms)で過渡音を捉え、遅い(1秒)で安定した読みやすい値に。",
    "home.f3.title": "LAeq と統計",
    "home.f3.body":
      "最小・最大・エネルギー平均、そして等価騒音レベルLAeqをリアルタイム表示 — 騒音規制で用いられる指標です。",
    "home.f4.title": "CSV・PDF書き出し",
    "home.f4.body":
      "レベル履歴全体をCSVでダウンロード、または整ったPDF要約レポートを保存 — すべてデバイス上で生成。",
    "home.f5.title": "完全にプライベート",
    "home.f5.body":
      "音声はWeb Audio APIでローカルに解析され、即座に破棄されます。録音・保存・アップロードは一切ありません。",
    "home.f6.title": "あらゆる端末で動作",
    "home.f6.body":
      "完全な静的サイト — インストール不要、登録不要。スマホ・タブレット・ノートPCで開けばすぐに測定できます。",

    "home.scale.eyebrow": "参考",
    "home.scale.title": "デシベルの数字は何を意味する？",
    "home.scale.intro":
      "デシベルは対数です — 10 dB増えるごとに体感の大きさはおよそ倍になります。身近な音の比較は以下のとおりです。",
    "home.scale.callout.title": "85 dB のライン",
    "home.scale.callout.body":
      "NIOSHは推奨暴露限界を8時間で85 dBAとしています。これを超えると、3 dB増えるごとに1日の安全量は半減 — 88 dBAは4時間、91 dBAはわずか2時間だけ安全です。",
    "home.scale.link": "デシベル表の全文を見る →",

    "home.health.eyebrow": "なぜ重要か",
    "home.health.title": "騒音が多すぎる代償",
    "home.health.intro":
      "騒音は単なる不快さではありません。持続的な暴露は聴覚・睡眠・ストレス・集中力に測定可能な影響を及ぼします。",
    "home.h1.title": "騒音性難聴",
    "home.h1.body":
      "85 dBAを超える持続的な暴露は内耳を傷つけます。損失は徐々に、痛みもなく、不可逆的に進むため、症状が出る前のモニタリングが重要です。",
    "home.h2.title": "ストレスと心血管への負担",
    "home.h2.body":
      "慢性的な騒音は体を軽度のストレス状態に保ち、長期研究はこれを高血圧や心血管リスクの上昇と関連づけています。",
    "home.h3.title": "睡眠の妨げ",
    "home.h3.body":
      "夜間に約40 dBを超える騒音は、完全に目覚めなくても睡眠を分断します。寝室の騒音はこれより十分に低く保ちましょう。",
    "home.h4.title": "集中と学習",
    "home.h4.body":
      "背景騒音は注意を奪います。教室やオフィスでは理解力や記憶力を明確に低下させ、特に子どもへの影響が大きいです。",
    "home.health.note": "NIOSH、WHO、NIDCDの指針に基づいています。",

    "home.faq.eyebrow": "よくある質問",
    "home.faq.title": "オンライン騒音測定に関する質問",
    "home.faq.q1": "オンライン騒音計の精度は？",
    "home.faq.a1":
      "端末によります。スマホやノートPCのマイクは校正された計測器ではありませんが、校正オフセットを設定すれば日常レベルで概ね±3〜5 dB — 部屋の比較や傾向の把握には十分で、法的証拠にはなりません。",
    "home.faq.q2": "音声を録音・アップロードしますか？",
    "home.faq.a2":
      "いいえ。すべてWeb Audio APIでブラウザ内処理され、フレームごとに破棄されます。録音・保存・サーバー送信は一切ありません。",
    "home.faq.q3": "dBA・dBC・dBZ の違いは？",
    "home.faq.a3":
      "いずれも周波数重み付けです。dBAは人の聴覚を模し(聴覚リスクの標準)、dBCは低音をより多く捉え、dBZは未加工の重み付けなしスペクトルです。",
    "home.faq.q4": "どのくらいの音量が危険？",
    "home.faq.a4":
      "85 dBA以上への長時間暴露は永久的な難聴を招くおそれがあり、3 dB増えるごとに1日の安全量は半減します。120 dB以上の音は即座に害を与えることがあります。",
    "home.faq.more": "詳しくは完全版のFAQをご覧ください。",

    "home.cta.title": "騒音レベルを確認しませんか？",
    "home.cta.body":
      "上にスクロールして開始を押すか、デシベル表と暴露計算ツールで数値の意味を確かめてください。",
    "home.cta.measure": "測定を開始",
    "home.cta.chart": "デシベル表",
  },

  // ===========================================================================
  // 한국어 — Korean
  // ===========================================================================
  ko: {
    "common.skip": "본문으로 건너뛰기",
    "common.start": "측정 시작",
    "common.home": "홈",
    "common.language": "언어",
    "common.theme": "라이트 / 다크 전환",
    "common.menu.open": "메뉴 열기",
    "common.menu.close": "메뉴 닫기",
    "common.keyboard": "키보드 단축키",

    "nav.meter": "소음 측정기",
    "nav.decibelChart": "데시벨 표",
    "nav.safeExposure": "안전 노출",
    "nav.classroom": "교실",
    "nav.blog": "블로그",
    "nav.faq": "자주 묻는 질문",
    "nav.howItWorks": "작동 원리",
    "nav.accuracy": "정확도와 보정",
    "nav.about": "소개",
    "nav.methodology": "측정 방법",
    "nav.privacy": "개인정보",

    "footer.tools": "도구",
    "footer.learn": "학습",
    "footer.about": "소개",
    "footer.tagline":
      "브라우저에서 완전히 작동하는 무료 비공개 소음 측정기입니다. 오디오는 기기를 벗어나지 않습니다.",
    "footer.rights": "모든 측정값은 참고용 추정치입니다.",
    "footer.sources": "정확성을 위해 제작 · 출처",

    "meter.aria": "실시간 소음 측정기",
    "meter.idle": "마이크 대기 중",
    "meter.measuring": "측정 중…",
    "meter.unavailable": "사용 불가",
    "meter.weight": "가중",
    "meter.fast": "빠름",
    "meter.slow": "느림",
    "meter.idleZone": "대기",
    "meter.min": "최소",
    "meter.max": "최대",
    "meter.avg": "평균",
    "meter.leq": "LAeq",
    "meter.spectrum": "주파수 스펙트럼",
    "meter.spectrumHint": "측정을 시작하면 실시간 스펙트럼이 표시됩니다",
    "meter.history": "레벨 기록 · 최근 60초",
    "meter.nioshLimit": "NIOSH 85 dB 한계",
    "meter.stop": "정지",
    "meter.reset": "초기화",
    "meter.calibrate": "보정",
    "meter.exportCsv": "CSV 내보내기",
    "meter.savePdf": "PDF 저장",
    "meter.note":
      "오디오는 로컬에서 처리되며 기기를 벗어나지 않습니다. 휴대폰이나 노트북 마이크는 보정된 측정기가 아니므로 측정값은 참고용 추정치입니다. 알려진 기준에 맞추려면 보정 오프셋을 사용하세요.",
    "meter.errUnsupported": "이 브라우저는 마이크 접근을 지원하지 않습니다.",
    "meter.errDenied":
      "마이크 권한이 거부되었습니다. 접근을 허용하고 새로 고침하여 측정하세요. 오디오는 기기에 남아 있습니다.",
    "meter.srSummary": "{db} 데시벨, {zone}. 평균 {avg}, 최대 {max}.",
    "meter.report.title": "소음 레벨 보고서",
    "meter.report.average": "평균",
    "meter.report.metric": "항목",
    "meter.report.value": "값",
    "meter.report.note":
      "Online Sound Meter로 생성됨. 측정값은 일반 마이크의 보정되지 않은 참고용 추정치이며, 1/2종 소음계를 대체하지 않습니다. 출처: NIOSH, WHO, NIDCD.",

    "zone.quiet": "조용함",
    "zone.moderate": "보통",
    "zone.elevated": "다소 높음",
    "zone.loud": "시끄러움",
    "zone.danger": "위험",

    "banner.text": "이 페이지는 사용 중인 언어로도 제공됩니다.",
    "banner.cta": "{lang}(으)로 보기",
    "banner.dismiss": "닫기",

    "kbd.title": "키보드 단축키",
    "kbd.subtitle": "마우스 없이 측정기를 탐색하고 제어하세요.",
    "kbd.close": "닫기",
    "kbd.group.meter": "측정기",
    "kbd.group.nav": "탐색",
    "kbd.group.general": "일반",
    "kbd.meter.toggle": "측정 시작 / 정지",
    "kbd.meter.reset": "통계 초기화",
    "kbd.meter.weight": "가중 전환 (A / C / Z)",
    "kbd.meter.response": "빠름 / 느림 전환",
    "kbd.meter.csv": "CSV 내보내기",
    "kbd.nav.hint": "g를 누른 다음 키를 누르세요:",
    "kbd.nav.home": "측정기(홈)로 이동",
    "kbd.nav.decibel": "데시벨 표로 이동",
    "kbd.nav.exposure": "안전 노출 계산기로 이동",
    "kbd.nav.classroom": "교실용 측정기로 이동",
    "kbd.nav.blog": "블로그로 이동",
    "kbd.nav.faq": "자주 묻는 질문으로 이동",
    "kbd.general.help": "이 도움말 표시 / 숨기기",
    "kbd.general.theme": "라이트 / 다크 테마 전환",
    "kbd.general.lang": "언어 메뉴 열기",
    "kbd.general.esc": "대화상자 / 메뉴 닫기",

    "home.hero.eyebrow": "무료 온라인 소음 측정기",
    "home.hero.title": "브라우저에서 바로 소음을 데시벨로 측정하세요",
    "home.hero.subtitle":
      "전문가가 기대하는 지표를 갖춘 빠르고 비공개적인 소음 측정기 — dBA, LAeq, 주파수 가중, 시간 응답. 앱 없이, 업로드 없이, 가입 없이.",
    "home.hero.tip":
      "팁: 요청 시 마이크 접근을 허용하세요. 가장 정확한 값을 얻으려면 알려진 기준에 대해 보정 오프셋을 설정하세요.",

    "home.features.eyebrow": "이 측정기를 쓰는 이유",
    "home.features.title": "단순한 숫자 그 이상",
    "home.features.intro":
      "대부분의 온라인 측정기는 수치 하나만 보여주고 끝납니다. 이 도구는 실제 측정에 필요한 가중, 시간 응답, 통계를 단순함을 잃지 않고 제공합니다.",
    "home.f1.title": "A / C / Z 가중",
    "home.f1.body":
      "청력 위험 평가를 위한 A 가중, 저주파와 피크 소음을 위한 C, 가중되지 않은 스펙트럼을 위한 Z 사이를 전환하세요.",
    "home.f2.title": "빠름 & 느림 응답",
    "home.f2.body":
      "표준 IEC 61672 시간 가중 — 빠름(125ms)으로 순간음을 잡고, 느림(1초)으로 안정적이고 읽기 쉬운 값을 얻습니다.",
    "home.f3.title": "LAeq & 통계",
    "home.f3.body":
      "실시간 최소·최대·에너지 평균과 등가 소음 레벨 LAeq — 소음 규정에서 사용하는 지표입니다.",
    "home.f4.title": "CSV & PDF 내보내기",
    "home.f4.body":
      "전체 레벨 기록을 CSV로 내려받거나 깔끔한 PDF 요약 보고서로 저장하세요 — 모두 기기에서 생성됩니다.",
    "home.f5.title": "완전히 비공개",
    "home.f5.body":
      "오디오는 Web Audio API로 로컬에서 분석되고 즉시 폐기됩니다. 녹음·저장·업로드되는 것은 전혀 없습니다.",
    "home.f6.title": "모든 기기에서 작동",
    "home.f6.body":
      "순수 정적 사이트 — 설치 없이, 가입 없이. 휴대폰·태블릿·노트북에서 열면 바로 측정할 수 있습니다.",

    "home.scale.eyebrow": "참고",
    "home.scale.title": "데시벨 숫자는 무엇을 의미하나요?",
    "home.scale.intro":
      "데시벨은 로그 단위입니다 — 10 dB 증가할 때마다 체감 음량은 대략 두 배가 됩니다. 일상적인 소리의 비교는 다음과 같습니다.",
    "home.scale.callout.title": "85 dB 경계선",
    "home.scale.callout.body":
      "NIOSH는 권장 노출 한계를 8시간에 85 dBA로 정합니다. 이를 넘으면 3 dB 증가할 때마다 하루 안전 허용량이 절반으로 줄어 — 88 dBA는 4시간, 91 dBA는 단 2시간만 안전합니다.",
    "home.scale.link": "전체 데시벨 표 보기 →",

    "home.health.eyebrow": "왜 중요한가",
    "home.health.title": "지나친 소음의 대가",
    "home.health.intro":
      "소음은 단순한 불편이 아닙니다. 지속적인 노출은 청력·수면·스트레스·집중력에 측정 가능한 영향을 미칩니다.",
    "home.h1.title": "소음성 난청",
    "home.h1.body":
      "85 dBA 이상에 지속적으로 노출되면 내이가 손상됩니다. 손실은 서서히, 통증 없이, 영구적으로 진행되므로 증상이 나타나기 전에 관찰하는 것이 중요합니다.",
    "home.h2.title": "스트레스와 심혈관 부담",
    "home.h2.body":
      "만성 소음은 몸을 가벼운 스트레스 상태로 유지하며, 장기 연구는 이를 높은 혈압과 심혈관 위험과 연관 짓습니다.",
    "home.h3.title": "수면 방해",
    "home.h3.body":
      "약 40 dB를 넘는 야간 소음은 완전히 깨지 않아도 수면을 끊을 수 있습니다. 침실 소음은 이보다 충분히 낮게 유지하세요.",
    "home.h4.title": "집중력과 학습",
    "home.h4.body":
      "배경 소음은 주의를 빼앗습니다. 교실과 사무실에서 이해력과 기억력을 뚜렷이 떨어뜨리며, 특히 어린이가 큰 영향을 받습니다.",
    "home.health.note": "NIOSH, WHO, NIDCD의 지침을 참고했습니다.",

    "home.faq.eyebrow": "자주 묻는 질문",
    "home.faq.title": "온라인 소음 측정에 관한 질문",
    "home.faq.q1": "온라인 소음 측정기는 얼마나 정확한가요?",
    "home.faq.a1":
      "기기에 따라 다릅니다. 휴대폰·노트북 마이크는 보정된 기기가 아니지만, 보정 오프셋을 설정하면 일상적인 레벨에서 대략 ±3~5 dB — 공간 비교와 추세 파악에는 충분하지만 법적 증거로는 쓸 수 없습니다.",
    "home.faq.q2": "오디오를 녹음하거나 업로드하나요?",
    "home.faq.a2":
      "아니요. 모든 처리는 Web Audio API로 브라우저에서 이루어지고 프레임 단위로 폐기됩니다. 녹음·저장·서버 전송은 전혀 없습니다.",
    "home.faq.q3": "dBA, dBC, dBZ의 차이는 무엇인가요?",
    "home.faq.a3":
      "모두 주파수 가중입니다. dBA는 사람의 청각을 모사하고(청력 위험의 표준), dBC는 저음을 더 많이 담으며, dBZ는 가중되지 않은 원시 스펙트럼입니다.",
    "home.faq.q4": "어느 정도의 소음이 위험한가요?",
    "home.faq.a4":
      "85 dBA 이상에 장시간 노출되면 영구적인 청력 손실이 생길 수 있고, 3 dB 증가할 때마다 하루 안전 허용량이 절반으로 줄어듭니다. 120 dB 이상의 소리는 즉각적인 손상을 일으킬 수 있습니다.",
    "home.faq.more": "전체 FAQ에서 더 보기.",

    "home.cta.title": "소음 수준을 확인할 준비가 되셨나요?",
    "home.cta.body":
      "위로 스크롤해 시작을 누르거나, 데시벨 표와 노출 계산기를 살펴보며 숫자의 의미를 알아보세요.",
    "home.cta.measure": "측정 시작",
    "home.cta.chart": "데시벨 표",
  },

  // ===========================================================================
  // Français — French
  // ===========================================================================
  fr: {
    "common.skip": "Aller au contenu",
    "common.start": "Démarrer la mesure",
    "common.home": "Accueil",
    "common.language": "Langue",
    "common.theme": "Basculer clair / sombre",
    "common.menu.open": "Ouvrir le menu",
    "common.menu.close": "Fermer le menu",
    "common.keyboard": "Raccourcis clavier",

    "nav.meter": "Sonomètre",
    "nav.decibelChart": "Tableau des décibels",
    "nav.safeExposure": "Exposition sûre",
    "nav.classroom": "Salle de classe",
    "nav.blog": "Blog",
    "nav.faq": "FAQ",
    "nav.howItWorks": "Fonctionnement",
    "nav.accuracy": "Précision et étalonnage",
    "nav.about": "À propos",
    "nav.methodology": "Méthodologie",
    "nav.privacy": "Confidentialité",

    "footer.tools": "Outils",
    "footer.learn": "Comprendre",
    "footer.about": "À propos",
    "footer.tagline":
      "Un sonomètre gratuit et privé qui fonctionne entièrement dans votre navigateur. L'audio ne quitte jamais votre appareil.",
    "footer.rights": "Toutes les mesures sont des estimations de référence.",
    "footer.sources": "Conçu pour la précision · Sources",

    "meter.aria": "Sonomètre en direct",
    "meter.idle": "Micro inactif",
    "meter.measuring": "Mesure…",
    "meter.unavailable": "Indisponible",
    "meter.weight": "Pond.",
    "meter.fast": "Rapide",
    "meter.slow": "Lent",
    "meter.idleZone": "Inactif",
    "meter.min": "Min",
    "meter.max": "Max",
    "meter.avg": "Moy",
    "meter.leq": "LAeq",
    "meter.spectrum": "Spectre de fréquence",
    "meter.spectrumHint": "Démarrez la mesure pour voir le spectre en direct",
    "meter.history": "Historique du niveau · 60 dernières s",
    "meter.nioshLimit": "Limite NIOSH 85 dB",
    "meter.stop": "Arrêter",
    "meter.reset": "Réinitialiser",
    "meter.calibrate": "Étalonner",
    "meter.exportCsv": "Exporter CSV",
    "meter.savePdf": "Enregistrer PDF",
    "meter.note":
      "L'audio est traité localement et ne quitte jamais votre appareil. Le micro d'un téléphone ou d'un ordinateur portable n'est pas un sonomètre étalonné : les mesures sont des estimations de référence. Utilisez le décalage d'étalonnage pour l'aligner sur une référence connue.",
    "meter.errUnsupported": "Ce navigateur ne prend pas en charge l'accès au micro.",
    "meter.errDenied":
      "Accès au micro refusé. Autorisez l'accès et rechargez pour mesurer. L'audio reste sur votre appareil.",
    "meter.srSummary": "{db} décibels, {zone}. Moyenne {avg}, max {max}.",
    "meter.report.title": "Rapport de niveau sonore",
    "meter.report.average": "moyenne",
    "meter.report.metric": "Indicateur",
    "meter.report.value": "Valeur",
    "meter.report.note":
      "Généré par Online Sound Meter. Les mesures sont des estimations de référence non étalonnées d'un micro grand public, pas un substitut à un sonomètre de classe 1/2. Sources : NIOSH, WHO, NIDCD.",

    "zone.quiet": "Calme",
    "zone.moderate": "Modéré",
    "zone.elevated": "Élevé",
    "zone.loud": "Fort",
    "zone.danger": "Danger",

    "banner.text": "Cette page est aussi disponible dans votre langue.",
    "banner.cta": "Voir en {lang}",
    "banner.dismiss": "Ignorer",

    "kbd.title": "Raccourcis clavier",
    "kbd.subtitle": "Naviguez et pilotez le sonomètre sans la souris.",
    "kbd.close": "Fermer",
    "kbd.group.meter": "Sonomètre",
    "kbd.group.nav": "Navigation",
    "kbd.group.general": "Général",
    "kbd.meter.toggle": "Démarrer / arrêter la mesure",
    "kbd.meter.reset": "Réinitialiser les statistiques",
    "kbd.meter.weight": "Changer la pondération (A / C / Z)",
    "kbd.meter.response": "Basculer réponse rapide / lente",
    "kbd.meter.csv": "Exporter CSV",
    "kbd.nav.hint": "Appuyez sur g puis une touche :",
    "kbd.nav.home": "Aller au sonomètre (accueil)",
    "kbd.nav.decibel": "Aller au tableau des décibels",
    "kbd.nav.exposure": "Aller au calculateur d'exposition sûre",
    "kbd.nav.classroom": "Aller au sonomètre de classe",
    "kbd.nav.blog": "Aller au blog",
    "kbd.nav.faq": "Aller à la FAQ",
    "kbd.general.help": "Afficher / masquer cette aide",
    "kbd.general.theme": "Basculer le thème clair / sombre",
    "kbd.general.lang": "Ouvrir le menu des langues",
    "kbd.general.esc": "Fermer la boîte de dialogue / le menu",

    "home.hero.eyebrow": "Sonomètre en ligne gratuit",
    "home.hero.title": "Mesurez le bruit en décibels, directement dans votre navigateur",
    "home.hero.subtitle":
      "Un sonomètre rapide et privé avec les indicateurs attendus des professionnels — dBA, LAeq, pondération fréquentielle et réponse temporelle. Sans application, sans téléversement, sans inscription.",
    "home.hero.tip":
      "Astuce : autorisez l'accès au micro lorsque c'est demandé. Pour des valeurs les plus précises, définissez un décalage d'étalonnage par rapport à une référence connue.",

    "home.features.eyebrow": "Pourquoi ce sonomètre",
    "home.features.title": "Plus qu'un simple chiffre",
    "home.features.intro":
      "La plupart des sonomètres en ligne affichent un chiffre et s'arrêtent là. Celui-ci vous donne les pondérations, la réponse temporelle et les statistiques nécessaires à une vraie mesure, sans perdre en simplicité.",
    "home.f1.title": "Pondération A / C / Z",
    "home.f1.body":
      "Basculez entre la pondération A pour le risque auditif, C pour le bruit basse fréquence et les crêtes, ou Z pour le spectre non pondéré.",
    "home.f2.title": "Réponse rapide & lente",
    "home.f2.body":
      "Pondérations temporelles standard IEC 61672 — Rapide (125 ms) pour capter les transitoires, Lente (1 s) pour des niveaux stables et lisibles.",
    "home.f3.title": "LAeq & statistiques",
    "home.f3.body":
      "Min, Max, moyenne énergétique et niveau continu équivalent LAeq en direct — l'indicateur utilisé dans la réglementation du bruit.",
    "home.f4.title": "Export CSV & PDF",
    "home.f4.body":
      "Téléchargez tout l'historique des niveaux en CSV, ou enregistrez un rapport de synthèse en PDF — généré sur votre appareil.",
    "home.f5.title": "Totalement privé",
    "home.f5.body":
      "L'audio est analysé localement avec la Web Audio API et écarté immédiatement. Rien n'est enregistré, stocké ni téléversé.",
    "home.f6.title": "Fonctionne sur tout appareil",
    "home.f6.body":
      "Un site purement statique — sans installation, sans inscription. Ouvrez-le sur un téléphone, une tablette ou un portable et mesurez aussitôt.",

    "home.scale.eyebrow": "Référence",
    "home.scale.title": "Que signifient les chiffres en décibels ?",
    "home.scale.intro":
      "Les décibels sont logarithmiques — chaque hausse de 10 dB double environ la sonorité perçue. Voici comment se comparent les sons du quotidien.",
    "home.scale.callout.title": "La ligne des 85 dB",
    "home.scale.callout.body":
      "Le NIOSH fixe la limite d'exposition recommandée à 85 dBA sur 8 heures. Au-delà, votre dose quotidienne sûre est divisée par deux tous les 3 dB — 88 dBA n'est sûr que 4 heures, et 91 dBA seulement 2.",
    "home.scale.link": "Voir le tableau complet des décibels →",

    "home.health.eyebrow": "Pourquoi c'est important",
    "home.health.title": "Le coût d'un excès de bruit",
    "home.health.intro":
      "Le bruit n'est pas qu'une gêne. Une exposition prolongée a des effets mesurables sur l'audition, le sommeil, le stress et la concentration.",
    "home.h1.title": "Perte auditive due au bruit",
    "home.h1.body":
      "Une exposition prolongée au-dessus de 85 dBA endommage l'oreille interne. La perte est progressive, indolore et permanente — d'où l'importance de surveiller avant l'apparition des symptômes.",
    "home.h2.title": "Stress et charge cardiovasculaire",
    "home.h2.body":
      "Le bruit chronique maintient le corps dans un léger état de stress, que des études à long terme associent à une tension plus élevée et à un risque cardiovasculaire accru.",
    "home.h3.title": "Perturbation du sommeil",
    "home.h3.body":
      "Un bruit nocturne au-dessus d'environ 40 dB peut fragmenter le sommeil même sans réveil complet. Gardez le bruit de la chambre bien en dessous.",
    "home.h4.title": "Concentration et apprentissage",
    "home.h4.body":
      "Le bruit de fond mobilise l'attention. En classe et au bureau, il réduit de façon mesurable la compréhension et la mémoire — les enfants surtout.",
    "home.health.note": "D'après les recommandations du NIOSH, de l'OMS et du NIDCD.",

    "home.faq.eyebrow": "FAQ",
    "home.faq.title": "Questions sur la mesure du son en ligne",
    "home.faq.q1": "Quelle est la précision d'un sonomètre en ligne ?",
    "home.faq.a1":
      "Cela dépend de votre appareil. Les micros de téléphone et d'ordinateur ne sont pas des instruments étalonnés, mais avec un décalage d'étalonnage, comptez environ ±3–5 dB pour les niveaux courants — assez pour comparer des pièces et suivre des tendances, pas comme preuve légale.",
    "home.faq.q2": "Cela enregistre-t-il ou téléverse-t-il mon audio ?",
    "home.faq.a2":
      "Non. Tout est traité dans votre navigateur avec la Web Audio API et écarté image par image. Rien n'est enregistré, stocké ni envoyé à un serveur.",
    "home.faq.q3": "Quelle est la différence entre dBA, dBC et dBZ ?",
    "home.faq.a3":
      "Ce sont des pondérations fréquentielles. dBA imite l'oreille humaine (la norme pour le risque auditif), dBC capte plus de graves, et dBZ est le spectre brut, non pondéré.",
    "home.faq.q4": "Quel niveau sonore est dangereux ?",
    "home.faq.a4":
      "Une exposition prolongée à 85 dBA ou plus peut causer une perte auditive permanente, et la dose quotidienne sûre est divisée par deux tous les 3 dB. Les sons de 120 dB et plus peuvent causer un dommage immédiat.",
    "home.faq.more": "Plus dans notre FAQ complète.",

    "home.cta.title": "Prêt à vérifier vos niveaux de bruit ?",
    "home.cta.body":
      "Remontez et appuyez sur démarrer, ou explorez le tableau des décibels et le calculateur d'exposition pour comprendre vos chiffres.",
    "home.cta.measure": "Démarrer la mesure",
    "home.cta.chart": "Tableau des décibels",
  },

  // ===========================================================================
  // Português — Portuguese
  // ===========================================================================
  pt: {
    "common.skip": "Pular para o conteúdo",
    "common.start": "Começar a medir",
    "common.home": "Início",
    "common.language": "Idioma",
    "common.theme": "Alternar claro / escuro",
    "common.menu.open": "Abrir menu",
    "common.menu.close": "Fechar menu",
    "common.keyboard": "Atalhos de teclado",

    "nav.meter": "Medidor",
    "nav.decibelChart": "Tabela de decibéis",
    "nav.safeExposure": "Exposição segura",
    "nav.classroom": "Sala de aula",
    "nav.blog": "Blog",
    "nav.faq": "Perguntas frequentes",
    "nav.howItWorks": "Como funciona",
    "nav.accuracy": "Precisão e calibração",
    "nav.about": "Sobre",
    "nav.methodology": "Metodologia",
    "nav.privacy": "Privacidade",

    "footer.tools": "Ferramentas",
    "footer.learn": "Aprender",
    "footer.about": "Sobre",
    "footer.tagline":
      "Um medidor de nível sonoro gratuito e privado que roda inteiramente no seu navegador. O áudio nunca sai do seu dispositivo.",
    "footer.rights": "Todas as leituras são estimativas de referência.",
    "footer.sources": "Feito para precisão · Fontes",

    "meter.aria": "Medidor de som ao vivo",
    "meter.idle": "Microfone inativo",
    "meter.measuring": "Medindo…",
    "meter.unavailable": "Indisponível",
    "meter.weight": "Pond.",
    "meter.fast": "Rápido",
    "meter.slow": "Lento",
    "meter.idleZone": "Inativo",
    "meter.min": "Mín",
    "meter.max": "Máx",
    "meter.avg": "Méd",
    "meter.leq": "LAeq",
    "meter.spectrum": "Espectro de frequência",
    "meter.spectrumHint": "Comece a medir para ver o espectro ao vivo",
    "meter.history": "Histórico de nível · últimos 60 s",
    "meter.nioshLimit": "Limite NIOSH 85 dB",
    "meter.stop": "Parar",
    "meter.reset": "Redefinir",
    "meter.calibrate": "Calibrar",
    "meter.exportCsv": "Exportar CSV",
    "meter.savePdf": "Salvar PDF",
    "meter.note":
      "O áudio é processado localmente e nunca sai do seu dispositivo. O microfone de um celular ou notebook não é um medidor calibrado — as leituras são estimativas de referência. Use o ajuste de calibração para alinhar com uma referência conhecida.",
    "meter.errUnsupported": "Este navegador não suporta acesso ao microfone.",
    "meter.errDenied":
      "Permissão do microfone negada. Permita o acesso e recarregue para medir. O áudio permanece no seu dispositivo.",
    "meter.srSummary": "{db} decibéis, {zone}. Média {avg}, máximo {max}.",
    "meter.report.title": "Relatório de nível sonoro",
    "meter.report.average": "média",
    "meter.report.metric": "Métrica",
    "meter.report.value": "Valor",
    "meter.report.note":
      "Gerado pelo Online Sound Meter. As leituras são estimativas de referência não calibradas de um microfone comum, não um substituto para um medidor de nível sonoro Tipo 1/2. Fontes: NIOSH, WHO, NIDCD.",

    "zone.quiet": "Silencioso",
    "zone.moderate": "Moderado",
    "zone.elevated": "Elevado",
    "zone.loud": "Alto",
    "zone.danger": "Perigo",

    "banner.text": "Esta página também está disponível no seu idioma.",
    "banner.cta": "Ver em {lang}",
    "banner.dismiss": "Dispensar",

    "kbd.title": "Atalhos de teclado",
    "kbd.subtitle": "Navegue e controle o medidor sem usar o mouse.",
    "kbd.close": "Fechar",
    "kbd.group.meter": "Medidor",
    "kbd.group.nav": "Navegação",
    "kbd.group.general": "Geral",
    "kbd.meter.toggle": "Iniciar / parar medição",
    "kbd.meter.reset": "Redefinir estatísticas",
    "kbd.meter.weight": "Alternar ponderação (A / C / Z)",
    "kbd.meter.response": "Alternar resposta rápida / lenta",
    "kbd.meter.csv": "Exportar CSV",
    "kbd.nav.hint": "Pressione g e depois uma tecla:",
    "kbd.nav.home": "Ir para o medidor (início)",
    "kbd.nav.decibel": "Ir para a tabela de decibéis",
    "kbd.nav.exposure": "Ir para a calculadora de exposição segura",
    "kbd.nav.classroom": "Ir para o medidor de sala de aula",
    "kbd.nav.blog": "Ir para o blog",
    "kbd.nav.faq": "Ir para as perguntas frequentes",
    "kbd.general.help": "Mostrar / ocultar esta ajuda",
    "kbd.general.theme": "Alternar tema claro / escuro",
    "kbd.general.lang": "Abrir o menu de idiomas",
    "kbd.general.esc": "Fechar caixa de diálogo / menu",

    "home.hero.eyebrow": "Medidor de som online gratuito",
    "home.hero.title": "Meça o ruído em decibéis, direto no seu navegador",
    "home.hero.subtitle":
      "Um medidor de som rápido e privado com as métricas que os profissionais esperam — dBA, LAeq, ponderação de frequência e resposta temporal. Sem app, sem upload, sem cadastro.",
    "home.hero.tip":
      "Dica: permita o acesso ao microfone quando solicitado. Para os valores mais precisos, defina um ajuste de calibração em relação a uma referência conhecida.",

    "home.features.eyebrow": "Por que este medidor",
    "home.features.title": "Mais do que um único número",
    "home.features.intro":
      "A maioria dos medidores online mostra um número e para por aí. Este oferece as ponderações, a resposta temporal e as estatísticas que uma medição real precisa — sem perder a simplicidade.",
    "home.f1.title": "Ponderação A / C / Z",
    "home.f1.body":
      "Alterne entre a ponderação A para risco auditivo, C para ruído de baixa frequência e picos, ou Z para o espectro sem ponderação.",
    "home.f2.title": "Resposta rápida & lenta",
    "home.f2.body":
      "Ponderações temporais padrão IEC 61672 — Rápida (125 ms) para captar transientes, Lenta (1 s) para níveis estáveis e legíveis.",
    "home.f3.title": "LAeq & estatísticas",
    "home.f3.body":
      "Mín, Máx, média de energia e o nível contínuo equivalente LAeq ao vivo — a métrica usada nas normas de ruído.",
    "home.f4.title": "Exportar CSV & PDF",
    "home.f4.body":
      "Baixe todo o histórico de nível em CSV, ou salve um relatório resumido em PDF — gerado no seu dispositivo.",
    "home.f5.title": "Totalmente privado",
    "home.f5.body":
      "O áudio é analisado localmente com a Web Audio API e descartado na hora. Nada é gravado, armazenado ou enviado.",
    "home.f6.title": "Funciona em qualquer dispositivo",
    "home.f6.body":
      "Um site puramente estático — sem instalação, sem cadastro. Abra no celular, tablet ou notebook e comece a medir na hora.",

    "home.scale.eyebrow": "Referência",
    "home.scale.title": "O que significam os números de decibéis?",
    "home.scale.intro":
      "Decibéis são logarítmicos — cada aumento de 10 dB praticamente dobra a sonoridade percebida. Veja como os sons do dia a dia se comparam.",
    "home.scale.callout.title": "A linha dos 85 dB",
    "home.scale.callout.body":
      "O NIOSH define o limite de exposição recomendado em 85 dBA por 8 horas. Acima disso, sua dose diária segura cai pela metade a cada 3 dB extras — 88 dBA é seguro por apenas 4 horas, e 91 dBA por só 2.",
    "home.scale.link": "Ver a tabela completa de decibéis →",

    "home.health.eyebrow": "Por que importa",
    "home.health.title": "O custo de ruído em excesso",
    "home.health.intro":
      "Ruído não é só incômodo. A exposição contínua tem efeitos mensuráveis na audição, no sono, no estresse e na concentração.",
    "home.h1.title": "Perda auditiva por ruído",
    "home.h1.body":
      "A exposição contínua acima de 85 dBA danifica o ouvido interno. A perda é gradual, indolor e permanente — por isso medir importa antes que os sintomas apareçam.",
    "home.h2.title": "Estresse e sobrecarga cardiovascular",
    "home.h2.body":
      "O ruído crônico mantém o corpo em estresse leve, que estudos de longo prazo associam a pressão mais alta e maior risco cardiovascular.",
    "home.h3.title": "Distúrbio do sono",
    "home.h3.body":
      "Ruído noturno acima de cerca de 40 dB pode fragmentar o sono mesmo sem você acordar de todo. Mantenha o ruído do quarto bem abaixo disso.",
    "home.h4.title": "Concentração e aprendizado",
    "home.h4.body":
      "O ruído de fundo disputa a atenção. Em salas de aula e escritórios, reduz de forma mensurável a compreensão e a memória — as crianças mais de todas.",
    "home.health.note": "Baseado nas orientações do NIOSH, da OMS e do NIDCD.",

    "home.faq.eyebrow": "Perguntas frequentes",
    "home.faq.title": "Perguntas sobre medição de som online",
    "home.faq.q1": "Qual a precisão de um medidor de som online?",
    "home.faq.a1":
      "Depende do seu dispositivo. Microfones de celular e notebook não são instrumentos calibrados, mas com um ajuste de calibração espere cerca de ±3–5 dB em níveis cotidianos — suficiente para comparar ambientes e acompanhar tendências, não como prova legal.",
    "home.faq.q2": "Isso grava ou envia meu áudio?",
    "home.faq.a2":
      "Não. Tudo é processado no seu navegador com a Web Audio API e descartado quadro a quadro. Nada é gravado, armazenado ou enviado a um servidor.",
    "home.faq.q3": "Qual a diferença entre dBA, dBC e dBZ?",
    "home.faq.a3":
      "São ponderações de frequência. dBA imita a audição humana (o padrão para risco auditivo), dBC capta mais graves, e dBZ é o espectro bruto, sem ponderação.",
    "home.faq.q4": "Que nível de som é perigoso?",
    "home.faq.a4":
      "Exposição prolongada a 85 dBA ou mais pode causar perda auditiva permanente, e a dose diária segura cai pela metade a cada 3 dB extras. Sons de 120 dB ou mais podem causar dano imediato.",
    "home.faq.more": "Mais nas nossas perguntas frequentes completas.",

    "home.cta.title": "Pronto para conferir seus níveis de ruído?",
    "home.cta.body":
      "Volte ao topo e pressione começar, ou explore a tabela de decibéis e a calculadora de exposição para entender seus números.",
    "home.cta.measure": "Começar a medir",
    "home.cta.chart": "Tabela de decibéis",
  },
} as const;
